-- ============================================================
-- NIAS Academy - 015 down: restore pruned permissions.
-- Re-inserts the removed permission codes (no role mapping restore;
-- roles can be re-assigned afterwards).
-- ============================================================

INSERT INTO permissions (code, description) VALUES
    ('users.update', 'تعديل المستخدمين'),
    ('users.delete', 'حذف المستخدمين'),
    ('site_pages.publish', 'نشر صفحات'),
    ('news.publish', 'نشر أخبار'),
    ('gallery.read', 'قراءة المعرض'),
    ('gallery.create', 'إضافة معرض'),
    ('gallery.update', 'تعديل معرض'),
    ('gallery.delete', 'حذف معرض'),
    ('gallery.publish', 'نشر محتوى المعرض'),
    ('downloads.read', 'قراءة ملفات التحميل'),
    ('downloads.create', 'إضافة ملفات'),
    ('downloads.update', 'تعديل ملفات'),
    ('downloads.delete', 'حذف ملفات'),
    ('downloads.publish', 'نشر ملفات التحميل'),
    ('conferences.read', 'قراءة المؤتمرات'),
    ('conferences.create', 'إنشاء مؤتمرات'),
    ('conferences.update', 'تعديل مؤتمرات'),
    ('conferences.delete', 'حذف مؤتمرات'),
    ('conferences.publish', 'نشر المؤتمرات'),
    ('trustees.read', 'قراءة أعضاء مجلس الأمناء'),
    ('trustees.create', 'إضافة أعضاء'),
    ('trustees.update', 'تعديل أعضاء'),
    ('trustees.delete', 'حذف أعضاء'),
    ('trustees.publish', 'نشر أعضاء مجلس الأمناء'),
    ('institute_branches.read', 'قراءة الفروع'),
    ('institute_branches.create', 'إضافة فروع'),
    ('institute_branches.update', 'تعديل فروع'),
    ('institute_branches.delete', 'حذف فروع'),
    ('colleges.read', 'قراءة الكليات'),
    ('colleges.create', 'إضافة كليات'),
    ('colleges.update', 'تعديل كليات'),
    ('colleges.delete', 'حذف كليات'),
    ('departments.read', 'قراءة الأقسام'),
    ('departments.create', 'إضافة أقسام'),
    ('departments.update', 'تعديل أقسام'),
    ('departments.delete', 'حذف أقسام'),
    ('faculty_members.read', 'قراءة أعضاء هيئة التدريس'),
    ('faculty_members.create', 'إضافة أعضاء'),
    ('faculty_members.update', 'تعديل أعضاء'),
    ('faculty_members.delete', 'حذف أعضاء'),
    ('program_plans.read', 'قراءة خطط البرامج'),
    ('program_plans.create', 'رفع خطط'),
    ('program_plans.update', 'تعديل خطط'),
    ('program_plans.delete', 'حذف خطط'),
    ('applicants.read', 'قراءة المتقدمين'),
    ('applications.read', 'قراءة الطلبات'),
    ('applications.update', 'تعديل الطلبات'),
    ('applications.review', 'مراجعة الطلبات (قبول/رفض)'),
    ('students.read', 'قراءة بيانات الطلاب'),
    ('students.update', 'تعديل بيانات الطلاب'),
    ('student_results.read', 'قراءة النتائج'),
    ('student_documents.read', 'قراءة وثائق الطالب'),
    ('elearning_courses.read', 'قراءة مقررات التعليم الإلكتروني'),
    ('elearning_courses.create', 'إنشاء مقررات'),
    ('elearning_courses.update', 'تعديل مقررات'),
    ('elearning_courses.delete', 'حذف مقررات'),
    ('elearning_lessons.read', 'قراءة الدروس'),
    ('elearning_lessons.create', 'إضافة دروس'),
    ('elearning_lessons.update', 'تعديل دروس'),
    ('elearning_lessons.delete', 'حذف دروس'),
    ('elearning_enrollments.read', 'قراءة تسجيلات المقررات'),
    ('elearning_enrollments.update', 'تحديث تسجيلات المقررات'),
    ('training_users.update', 'تعديل المتدربين'),
    ('training_enrollments.update', 'تحديث تسجيلات التدريب'),
    ('journal_categories.read', 'قراءة تصنيفات المجلة'),
    ('journal_categories.create', 'إنشاء تصنيفات'),
    ('journal_categories.update', 'تعديل تصنيفات'),
    ('journal_categories.delete', 'حذف تصنيفات'),
    ('journal_issues.read', 'قراءة أعداد المجلة'),
    ('journal_issues.create', 'إنشاء أعداد'),
    ('journal_issues.update', 'تعديل أعداد'),
    ('journal_issues.delete', 'حذف أعداد'),
    ('journal_issues.publish', 'نشر أعداد'),
    ('journal_articles.read', 'قراءة المقالات'),
    ('journal_articles.create', 'إنشاء مقالات'),
    ('journal_articles.update', 'تعديل مقالات'),
    ('journal_articles.delete', 'حذف مقالات'),
    ('journal_articles.publish', 'نشر مقالات'),
    ('journal_editorial_board.read', 'قراءة هيئة التحرير'),
    ('journal_editorial_board.create', 'إضافة أعضاء'),
    ('journal_editorial_board.update', 'تعديل أعضاء'),
    ('journal_editorial_board.delete', 'حذف أعضاء'),
    ('settings.read', 'قراءة إعدادات الموقع'),
    ('settings.update', 'تعديل إعدادات الموقع'),
    ('audit_logs.read', 'قراءة سجلات التدقيق'),
    ('admission_periods.read', 'قراءة فترات القبول'),
    ('admission_periods.create', 'إنشاء فترات قبول'),
    ('admission_periods.update', 'تعديل فترات قبول'),
    ('admission_periods.delete', 'حذف فترات قبول'),
    ('training_attendance.read', 'قراءة حضور المتدربين'),
    ('training_attendance.create', 'تسجيل حضور'),
    ('training_attendance.update', 'تعديل حضور'),
    ('training_certificates.read', 'قراءة شهادات التدريب'),
    ('training_certificates.create', 'إصدار شهادات'),
    ('training_certificates.update', 'تعديل شهادات'),
    ('training_reports.read', 'قراءة تقارير التدريب'),
    ('trainers.read', 'قراءة المدربين'),
    ('trainers.create', 'إضافة مدربين'),
    ('trainers.update', 'تعديل مدربين'),
    ('trainers.delete', 'حذف مدربين'),
    ('conference_submissions.read', 'قراءة ملفات المؤتمرات'),
    ('conference_submissions.create', 'إرسال ملفات المؤتمرات'),
    ('conference_submissions.update', 'تعديل ملفات المؤتمرات'),
    ('conference_submissions.delete', 'حذف ملفات المؤتمرات')
ON CONFLICT (code) DO NOTHING;